### ISSUE TITLE
Error generating images

### ISSUE THREAD

**Issue by wogam** [xingqian2018/sd-webui-prompt-free-diffusion#1]
>     Traceback (most recent call last):
>       File "E:\stable-diffusion-webui\modules\call_queue.py", line 55, in f
>         res = list(func(*args, **kwargs))
>       File "E:\stable-diffusion-webui\modules\call_queue.py", line 35, in f
>         res = func(*args, **kwargs)
>       File "E:\stable-diffusion-webui\modules\txt2img.py", line 57, in txt2img
>         processed = processing.process_images(p)
>       File "E:\stable-diffusion-webui\modules\processing.py", line 620, in process_images
>         res = process_images_inner(p)
>       File "E:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 42, in processing_process_images_hijack
>         return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
>       File "E:\stable-diffusion-webui\modules\processing.py", line 729, in process_images_inner
>         p.setup_conds()
>       File "E:\stable-diffusion-webui\extensions\sd-webui-prompt-free-diffusion\scripts\pfd.py", line 371, in setup_conds
>         self.uc = self.get_conds_with_caching(
>     TypeError: StableDiffusionProcessing.get_conds_with_caching() missing 1 required positional argument: 'extra_network_data'

Windows, latest A1111, model placed in folder, settings as below
![image](https://github.com/xingqian2018/sd-webui-prompt-free-diffusion/assets/48340127/ab8aad23-9821-430b-8361-7174c273d51e)

**Comment by xingqian2018** [comment]
Should be fixed
